- hosts: masters
  remote_user: pc
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  vars:
    helm_chart_url: "https://helm.cilium.io/"
    
  vars_prompt:

   - name: "pod_network_cidr"
     prompt: "Entre le Pod Network CIDR, exemple: 192.168.0.0/16"
     private: no

   - name: "k8s_master_ip"
     prompt: "Entre l'Apiserver advertise address, exemple: 192.168.222.147"
     private: no


  tasks:

   - name: Init du cluster kube
     command: kubeadm init --pod-network-cidr "{{ pod_network_cidr }}"  --apiserver-advertise-address "{{ k8s_master_ip }}"
     run_once: true
     delegate_to: "{{ k8s_master_ip }}"

   - pause: seconds=30

   - name: Cree le dossier kube config.
     become_user: pc
     become_method: sudo
     become: yes
     file:
       path: /home/{{ansible_user }}/.kube
       state: directory
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: 0755

   - name: Copy /etc/kubernetes/admin.conf vers le répertoire personnel de l'utilisateur /home/{{ ansible_user }}/.kube/config.
     become_user: root
     become_method: sudo
     become: yes
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/{{ ansible_user }}/.kube/config
       remote_src: yes
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: '0644'

   - pause: seconds=30

   - name: supprime le cache du dossier kube.
     become_user: pc
     become_method: sudo
     become: yes
     file:
       path: /home/{{ ansible_user }}/.kube/cache
       state: absent
  
   - name: Ajout repo helm
     kubernetes.core.helm_repository:
       name: cilium
       repo_name: cilium
       repo_url: "{{ helm_chart_url }}"
       repo_state: present



   - name: helm repo update
     kubernetes.core.helm:
       state: absent
       binary_path: /usr/local/bin/helm
       name: cilium # tricks needed to refresh in separate step
       namespace: default
       update_repo_cache: true
       kubeconfig: /etc/kubernetes/admin.conf



   
   - name: install cilium
     kubernetes.core.helm:
       name: pod-cilium
       namespace: kube-system
       chart_ref: cilium/cilium
       chart_version: 1.12.4
       kubeconfig: /etc/kubernetes/admin.conf
   - pause: seconds=30

   - name: Obtenez le jeton pour joindre les nœuds avec le maître Kuberentes.
     shell: kubeadm token create  --print-join-command
     register: kubernetes_join_command

   - debug:
       msg: "{{ kubernetes_join_command.stdout }}"

   - name: Copiez la commande de jointure dans le fichier local.
     become: false
     local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
...
